services:
  mariadb:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - myems-db-data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    # No need to expose ports externally
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  api:
    build: myems-api
    command: gunicorn app:api -b 0.0.0.0:8000 --timeout 600 --workers=4
    volumes:
      - /myems-upload:/var/www/myems-admin/upload
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env

  aggregation:
    build: myems-aggregation
    command: python main.py
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env

  cleaning:
    build: myems-cleaning
    command: python main.py
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env

  modbus_tcp:
    build: myems-modbus-tcp
    command: python main.py
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env

  normalization:
    build: myems-normalization
    command: python main.py
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env

  admin:
    build: myems-admin
    command: nginx -c /etc/nginx/nginx.conf -g "daemon off;"
    healthcheck:
      test: [ "CMD","nginx","-t" ]
    volumes:
      - /myems-upload:/var/www/myems-admin/upload
    restart: always
    ports:
      - "8001:8001"
  web:
    build: myems-web
    command: nginx -c /etc/nginx/nginx.conf -g "daemon off;"
    healthcheck:
      test: [ "CMD","nginx","-t" ]
    restart: always
    ports:
      - "80:80"

volumes:
  myems-db-data:
